backend/Controllers/admin/vagas/VagaController.cs
using backend.Models;
using backend.Models.Dtos;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace backend.Controllers.admin.vagas
{
    public class VagaController : Controller
    {
        // GET: Vaga
        public ActionResult Index(int pagina = 1)
        {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }

            var vagas = Vaga.listar().OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA);

            return View(vagas);
        }

        public ActionResult Cadastrar() {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }

            // Listando jornadas de trabalho
            var jornadas = VagaJornada.listar();
            ViewBag.Jornadas = jornadas;
            // Listando tipos de contratação
            var tiposContratacao = VagaTipo.listar();
            ViewBag.TiposContratacao = tiposContratacao;

            return View();
        }

        [HttpPost]
        public ActionResult CadastrarAction() {
            var usuario = Session["usuario"] as Usuario;
            var vaga = new Vaga();
            vaga.Cargo = Request.Form.Get("cargo");
            vaga.Quantidade = int.Parse(Request.Form.Get("quantidade"));
            vaga.Cidade = Request.Form.Get("cidade");
            vaga.Estado = Request.Form.Get("estado");
            vaga.Empresa = Request.Form.Get("empresa");
            vaga.Requisitos = Request.Form.Get("requisitos");
            vaga.Atribuicoes = Request.Form.Get("atribuicoes");
            vaga.Remuneracao = double.Parse(Request.Form.Get("remuneracao"));
            vaga.Beneficios = Request.Form.Get("beneficios");
            vaga.DataPostagem = DateTime.Now.Date.ToString();
            vaga.DataLimite = Request.Form.Get("dataLimite");
            vaga.Observacoes = Request.Form.Get("observacoes");
            vaga.VagaJornadaId = int.Parse(Request.Form.Get("jornada"));
            vaga.VagaTipoId = int.Parse(Request.Form.Get("tipo"));
            vaga.UsuarioId = usuario.Id;

            if (vaga.cadastrar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Vaga foi cadastrada.";
            } else {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Ocorreu um erro ao cadastrar vaga.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id) {
            // Vericação de usuário logado
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }

            // Listando jornadas de trabalho
            var jornadas = VagaJornada.listar();
            ViewBag.Jornadas = jornadas;
            // Listando tipos de contratação
            var tiposContratacao = VagaTipo.listar();
            ViewBag.TiposContratacao = tiposContratacao;

            var vaga = new Vaga();
            vaga.Id = id;

            return View(vaga.buscarPorId());
        }

        [HttpPost]
        public ActionResult EditarAction() {
            // Vericação de usuário logado
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            // Listando jornadas de trabalho
            var jornadas = VagaJornada.listar();
            ViewBag.Jornadas = jornadas;
            // Listando tipos de contratação
            var tiposContratacao = VagaTipo.listar();
            ViewBag.TiposContratacao = tiposContratacao;

            var vaga = new Vaga();
            vaga.Id = int.Parse(Request.Form.Get("id"));
            vaga.Cargo = Request.Form.Get("cargo");
            vaga.Quantidade = int.Parse(Request.Form.Get("quantidade"));
            vaga.Cidade = Request.Form.Get("cidade");
            vaga.Estado = Request.Form.Get("estado");
            vaga.Empresa = Request.Form.Get("empresa");
            vaga.Requisitos = Request.Form.Get("requisitos");
            vaga.Atribuicoes = Request.Form.Get("atribuicoes");
            vaga.Remuneracao = double.Parse(Request.Form.Get("remuneracao"));
            vaga.Beneficios = Request.Form.Get("beneficios");
            vaga.DataPostagem = DateTime.Now.Date.ToString();
            vaga.DataLimite = Request.Form.Get("dataLimite");
            vaga.Observacoes = Request.Form.Get("observacoes");
            vaga.VagaJornadaId = int.Parse(Request.Form.Get("jornada"));
            vaga.VagaTipoId = int.Parse(Request.Form.Get("tipo"));
            vaga.UsuarioId = usuario.Id;

            if (vaga.editar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Vaga foi editada.";
            } else {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Ocorreu um erro ao editar vaga.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id)
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1)
            {
                return RedirectToAction("Entrar", "Home");
            }
            var vaga = new Vaga();
            vaga.Id = id;
            if (vaga.apagar())
            {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Vaga foi apagada.";
            }
            else
            {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Ocorreu um erro ao deletar vaga.";
            }
            return RedirectToAction("Index");
        }

        public ActionResult Detalhar(int id)
        {
            if (Session["usuario"] == null)
            {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1)
            {
                return RedirectToAction("Entrar", "Home");
            }
            var vaga = new Vaga();
            vaga.Id = id;

            var vagaDetalhada = new DetalharVagaResponse();
            vagaDetalhada = vaga.buscarPorId().toDetalhar();
            return View(vagaDetalhada);
        }
        public ActionResult Buscar(string requisito, int pagina = 1) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vaga = new Vaga();
            var resp = vaga.buscarPorRequisito(requisito);
            if (resp == null) {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Nenhuma informação foi encontrada.";
                return RedirectToAction("Index");
            }
            return View(resp.OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA));
        }
    }
}

backend/Controllers/admin/vagas/VagaJornadaController.cs
using backend.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace backend.Controllers.admin.vagas
{
    public class VagaJornadaController : Controller
    {
        // GET: VagaJornada
        public ActionResult Index(int pagina = 1) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaJornadas = VagaJornada.listar().OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA);
            if (vagaJornadas == null || vagaJornadas.Count == 0) {
                TempData["alertInfo"] = "Epa, perai! Parece que não tem nenhum tipo de Jornada cadastrado!";
            }
            return View(vagaJornadas);
        }

        public ActionResult Cadastrar() {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarAction() {
            var vagaJornada = new VagaJornada();
            vagaJornada.Descricao = Request.Form["descricao"];
            if (vagaJornada.cadastrar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de Jornada " + vagaJornada.Descricao + " foi cadastrada.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao cadastrar tipo de jornada!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaJornada = new VagaJornada();
            vagaJornada.Id = id;

            return View(vagaJornada.buscarPorId());
        }

        [HttpPost]
        public ActionResult EditarAction() {
            var descricao = Request.Form["descricao"];
            var id = int.Parse(Request.Form["id"]);

            var vagaJornada = new VagaJornada();
            vagaJornada.Id = id;
            vagaJornada.Descricao = descricao;
            if (vagaJornada.editar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de Jornada " + vagaJornada.Descricao + " foi editada.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao editar tipo de jornada!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaJornada = new VagaJornada();
            vagaJornada.Id = id;
            if (vagaJornada.apagar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de Jornada foi apagada.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao apagar tipo de jornada!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Buscar(string descricao, int pagina = 1) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaJornada = new VagaJornada();
            var resp = vagaJornada.buscarPorDescricao(descricao);
            if (resp == null) {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Nenhuma informação foi encontrada.";
                return RedirectToAction("Index");
            }
            return View(resp.OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA));
        }
    }
}

backend/Controllers/admin/vagas/VagaTipoController.cs
using backend.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace backend.Controllers.admin.vagas
{
    public class VagaTipoController : Controller
    {
        // GET: VagaTipo
        public ActionResult Index(int pagina = 1)
        {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var tipoVagas = VagaTipo.listar().OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA);
            if (tipoVagas == null || tipoVagas.Count == 0) {
                TempData["alertInfo"] = "Epa, perai! Parece que não tem nenhum tipo de vaga cadastrado!";
            }
            return View(tipoVagas);
        }

        public ActionResult Cadastrar() {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult CadastrarAction() {
            var vagaTipo = new VagaTipo();
            vagaTipo.Descricao = Request.Form["descricao"];
            if (vagaTipo.cadastrar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de Jornada " + vagaTipo.Descricao + " foi cadastrado.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao cadastrar tipo de contrato!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Editar(int id) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaTipo = new VagaTipo();
            vagaTipo.Id = id;

            return View(vagaTipo.buscarPorId());
        }

        [HttpPost]
        public ActionResult EditarAction() {
            var descricao = Request.Form["descricao"];
            var id = int.Parse(Request.Form["id"]);

            var vagaTipo = new VagaTipo();
            vagaTipo.Id = id;
            vagaTipo.Descricao = descricao;
            if (vagaTipo.editar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de contrato " + vagaTipo.Descricao + " foi editado.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao editar tipo de contrato!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }

            return RedirectToAction("Index");
        }

        public ActionResult Apagar(int id) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaTipo = new VagaTipo();
            vagaTipo.Id = id;
            if (vagaTipo.apagar()) {
                TempData["alertSucesso"] = "Sucesso!";
                TempData["alertMensagem"] = "Tipo de Contrato foi apagado.";
            } else {
                TempData["alertErro"] = "Ocorreu um erro ao apagar tipo de contrato!";
                TempData["alertMensagem"] = "Verifique os dados e tente novamente.";
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Buscar(string descricao, int pagina = 1) {
            if (Session["usuario"] == null) {
                return RedirectToAction("Entrar", "Home");
            }
            var usuario = Session["usuario"] as Usuario;
            if (usuario.Tipo != 1) {
                return RedirectToAction("Entrar", "Home");
            }
            var vagaTipo = new VagaTipo();
            var resp = vagaTipo.buscarPorDescricao(descricao);
            if (resp == null) {
                TempData["alertErro"] = "Erro!";
                TempData["alertMensagem"] = "Nenhuma informação foi encontrada.";
                return RedirectToAction("Index");
            }
            return View(resp.OrderBy(p => p.Id).ToPagedList(pagina, backend.Models.Util.ITENS_POR_PAGINA));
        }
    }
}

backend/Views/Vaga/Cadastrar.cshtml
@{
    ViewBag.Title = "Cadastrar Vaga";
    var jornadas = ViewData["jornadas"] as List<backend.Models.VagaJornada>;
    var tiposContracao = ViewData["tiposContratacao"] as List<backend.Models.VagaTipo>;
}

<link href="~/Content/Css/form.css" rel="stylesheet" />
<div id="users-container" class="dashboard-container">
    <h1 class="page-title"><a href="/Vaga"><</a> Cadastrar vaga</h1>
    <div class="job-form">
        <form action="/Vaga/CadastrarAction" method="post" class="jValidator">
            <div class="double-input-container">
                <div class="input-container">
                    <label for="jornada">Jornada</label>
                    <select name="jornada" id="jornada" data-rules="pick">
                        <option value="" selected></option>
                        @foreach (var jornada in jornadas) {
                            <option value="@jornada.Id">@jornada.Descricao</option>
                        }
                    </select>
                </div>
                <div class="input-container">
                    <label for="tipo">Tipo de Contratação</label>
                    <select name="tipo" id="tipo" data-rules="pick">
                        <option value="" selected></option>
                        @foreach (var tipo in tiposContracao) {
                            <option value="@tipo.Id">@tipo.Descricao</option>
                        }
                    </select>
                </div>
            </div>
            <div class="double-input-container">
                <div class="input-container">
                    <label for="cargo">Cargo</label>
                    <input name="cargo" type="text" id="cargo" data-rules="required|max:50" />
                </div>
                <div class="input-container">
                    <label for="quantidade">Quantidade</label>
                    <input name="quantidade" type="text" id="quantidade" data-rules="required|max:3" />
                </div>
            </div>
            <div class="double-input-container">
                <div class="input-container">
                    <label for="cidade">Cidade</label>
                    <input name="cidade" type="text" id="cidade" data-rules="required|max:50" />
                </div>
                <div class="input-container">
                    <label for="estado">Estado</label>
                    <select name="estado" id="estado" data-rules="pick">
                        <option value="" selected></option>
                        <option value="SP"> São Paulo</option>
                    </select>
                </div>
            </div>
            <div class="double-input-container">
                <div class="input-container">
                    <label for="empresa">Empresa contratante</label>
                    <input name="empresa" type="text" id="empresa" data-rules="required|max:50" />
                </div>
                <div class="input-container">
                    <label for="remuneracao">Remuneração</label>
                    <input name="remuneracao" type="text" id="remuneracao" data-rules="required|max:10" />
                </div>
            </div>

            <div class="input-container">
                <label for="requisitos">Requisitos</label>
                <textarea name="requisitos" id="requisitos" data-rules="required|max:1000"></textarea>
            </div>
            <div class="input-container">
                <label for="atribuicoes">Atribuições</label>
                <textarea name="atribuicoes" id="atribuicoes" data-rules="required|max:1000"></textarea>
            </div>


            <div class="input-container">
                <label for="beneficios">Benefícios</label>
                <textarea name="beneficios" id="beneficios" data-rules="required|max:500"></textarea>
            </div>
            <div class="input-container">
                <label for="observacoes">Observações</label>
                <textarea name="observacoes" id="observacoes" data-rules="required|max:500"></textarea>
            </div>

            <div class="double-input-container">

                <div class="input-container">
                    <label for="dataLimite">Data limite</label>
                    <input name="dataLimite" type="text" id="dataLimite" data-rules="required" />
                </div>
            </div>
            <button type="submit" class="btn-form">Cadastrar</button>
        </form>
    </div>
</div>
<script src="~/Content/Js/Helpers/input-helper.js"></script>
<script src="~/Content/Js/validator.js"></script>
<script src="~/Content/Js/imask.js"></script>
<script>
    var dataLimite = IMask(
        document.getElementById('dataLimite'),
        {
            mask: Date,
            min: new Date(),
            max: new Date(3000, 0, 1),
            lazy: false
        });
    var remuneracao = IMask(
        document.getElementById('remuneracao'),
        {
            mask: Number,
            min: 0,
            max: 10000000,
            thousandsSeparator: '.'
        });
    var quantidade = IMask(
        document.getElementById('quantidade'),
        {
            mask: Number,
            min: 0,
            max: 10000,
            thousandsSeparator: '.'
        });
</script>

backend/Views/Vaga/Detalhar.cshtml
@model backend.Models.Dtos.DetalharVagaResponse 
@{
    ViewBag.Title = "Vaga - Detalhar";
    var vaga = Model;
}

<h2>Detalhar Vaga</h2>

<div class="card text-decoration-none text-black my-3">
    <div class="card-header d-flex justify-content-between">
        <div>
            <h5 class="p-0 m-0">@vaga.Cargo - @vaga.Localidade - @vaga.Quantidade Vagas - @vaga.Tipo - @vaga.Jornada</h5>
        </div>
        <div>
        </div>
    </div>
    <div class="card-body">
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Contratante: </span>@vaga.Contratante
        </p>
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Requisitos: </span>@vaga.Requisitos
        </p>
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Atribuições: </span>@vaga.Atribuicoes
        </p>
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Remuneração: </span>R$ @vaga.Remuneracao
        </p>
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Benefícios: </span>@vaga.Beneficios
        </p>
        <p class="card-text py-1 m-0">
            <span class="fw-bold">Observações: </span>@vaga.Observacoes
        </p>
    </div>
    <div class="card-footer text-muted d-flex justify-content-between">
        <div>
            <p class="m-0">Postado em: @vaga.DataPostagem Por: @vaga.Usuario - Expira em: @vaga.DataLimite</p>
        </div>
        <div>
            @Html.ActionLink(" ", "Editar", "Vaga", new { id = vaga.Id }, new { @class = "btn btn-warning far fa-edit" })
            @Html.ActionLink(" ", "Apagar", "Vaga", new { id = vaga.Id }, new { @class = "btn btn-danger far fa-trash-alt" })
        </div>
    </div>
</div>